return {}
-- {
--     -- TODO: confiugre this further, still some issues with it for me,
--     -- e.g. holding ctrl-n glitches the completion menu
--     "saghen/blink.cmp",
--     dependencies = { "rafamadriz/friendly-snippets" },
--     version = "1.*",
--     opts = {
--         keymap = {
--             preset = "default",
--         },
--
--         completion = {
--             menu = {
--                 draw = {
--                     columns = { { "label", "label_description", gap = 1 }, { "kind_icon" } },
--                     components = {
--                         kind_icon = {
--                             -- text = function(ctx)
--                             --     local kind_icon, _, _ = require("mini.icons").get("lsp", ctx.kind)
--                             --     return kind_icon
--                             -- end,
--                             -- (optional) use highlights from mini.icons
--                             highlight = function(ctx)
--                                 local _, hl, _ = require("mini.icons").get("lsp", ctx.kind)
--                                 return hl
--                             end,
--                         },
--                         kind = {
--                             -- (optional) use highlights from mini.icons
--                             highlight = function(ctx)
--                                 local _, hl, _ = require("mini.icons").get("lsp", ctx.kind)
--                                 return hl
--                             end,
--                         },
--                     },
--                 },
--             },
--             documentation = {
--                 auto_show = true,
--                 window = {
--                     border = "",
--                 },
--             },
--         },
--
--         signature = {
--             window = {
--                 border = "",
--             },
--         },
--         -- Default list of enabled providers defined so that you can extend it
--         -- elsewhere in your config, without redefining it, due to `opts_extend`
--         sources = {
--             default = { "lsp", "path", "snippets", "buffer" },
--         },
--         fuzzy = {
--             implementation = "prefer_rust_with_warning",
--             sorts = {
--                 "exact",
--                 -- defaults
--                 "score",
--                 "sort_text",
--             },
--         },
--     },
--     opts_extend = { "sources.default" },
-- },
--
-- {
--     "HiPhish/rainbow-delimiters.nvim",
--     enabled = false,
--     lazy = true,
-- },
--
-- {
--     "numToStr/Comment.nvim",
--     lazy = false,
--     opts = {
--         -- add any options here
--     },
--     config = function()
--         require("Comment").setup()
--     end,
-- },
